### PR TITLE
English version

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by ChrisBr** [comment]
@digitaltom but it came just to my mind that we also need to handle the questions different ...

**Comment by ChrisBr** [comment]
Maybe not giving the filename as parameter but e.g. ``mode=english`` which then takes the questions from json-data-english.json and the answers from /english subfolder?

**Comment by digitaltom** [comment]
screenshot_20170411_130202

**Comment by ChrisBr** [comment]
@digitaltom very nice :) Thanks :+1:

**Pull request merged**
